name: balancemanagement_app
description: A new Flutter application.

version: 2.0.3+25
#version: 2.0.3+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite:
  path:

  auto_size_text: ^3.0.0
  app_tracking_transparency: ^2.0.3
#  app_review: ^2.1.2+1
  in_app_review: ^2.0.10
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.1.0
  charts_flutter:
    path: lib_plugins/charts_flutter
#    mkdir -p lib_plugins/charts_flutter
#    cp -r ~/.pub-cache/hosted/pub.dev/charts_flutter-0.12.0/* lib_plugins/charts_flutter/
#  charts_flutter: ^0.12.0
#  flutter_lock_screen: ^2.0.1
  flutter_slidable: ^4.0.0
  flutter_riverpod: ^2.1.3
  google_mobile_ads: ^6.0.0
  local_auth: ^2.1.3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  syncfusion_flutter_gauges: ^30.1.39
  flutter_keyboard_visibility: ^6.0.0
  keyboard_actions: ^4.2.0
  math_expressions: ^3.0.0
#  infinity_page_view: ^1.0.0
#  page_view_indicators
#  intl: ^0.16.0
#  path_provider_macos: ^0.0.1
#  admob_flutter: ^1.0.1
#  win32: ^5.14.0
  material_design_icons_flutter: ^7.0.7296
  passcode_screen: ^2.0.1


dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
