name: balancemanagement_app
description: A new Flutter application.

version: 1.2.7+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  sqflite:
  path:
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.1
  intl: ^0.16.0
  auto_size_text: ^2.1.0
  path_provider: ^1.6.7
#  path_provider_macos: ^0.0.1
#  charts_flutter: ^0.9.0
  flutter_slidable: "^0.5.4"
  infinity_page_view: ^1.0.0
  flutter_google_ad_manager: 0.10.1
  flutter_store_listing: ^0.1.1+2
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
